language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - pip install nose
  - pip install docutils
  - pip install flask
  - pip install whoosh
  - pip install argparse
  - pip install PyYAML
script:
  tools/neorg-ci.sh
