language: python
before_install:
  - pip install --quiet tox sphinx
  - apt-cache policy coffeescript
  - sudo apt-get install coffeescript
script:
  - python setup.py build  # build sphinx document etc.
  - tox
env:
  - NEORG_FASTTEST=
  - NEORG_FASTTEST=t
