language: python
before_install:
  - pip install --quiet tox sphinx
  # Install new coffeescript
  - sudo apt-get install coffeescript
  - coffee --version
script:
  - tox
env:
  - NEORG_FASTTEST=
  - NEORG_FASTTEST=t
