language: python
before_install:
  - pip install --quiet tox sphinx
  # Install new coffeescript
  - sudo add-apt-repository -y ppa:gezakovacs/coffeescript
  - sudo apt-get update -qq
  - sudo apt-get install coffeescript
  - coffee --version
script:
  - python setup.py build  # build sphinx document etc.
  - tox
env:
  - NEORG_FASTTEST=
  - NEORG_FASTTEST=t
